/* Autogenerated by png2wx.pl on Wed May 11 19:39:15 2011 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_logbook_pi;
extern wxBitmap *_img_logbook;

#endif /* ICONS_H */
